---
- name: Install gnupg for the apt_key module
  apt:
    name: gnupg2
    update_cache: yes
    state: latest
  when: ansible_distribution != "Ubuntu" # there're no requirement for gnupg2 in any Ubuntu here 

- name: Install mono prerequisites for 18.04
  apt:
    name: ['gnupg', 'ca-certificates']
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- name: Install mono prerequisites for 14.04 && 16.04
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu" and (ansible_distribution_major_version == "16" or ansible_distribution_major_version == "14")


- name: Add mono apt key
  apt_key:
    keyserver: "{{ mono_apt_keyserver }}"
    id: "{{ mono_apt_key_id }}"
    state: present
# Not sure why this was added remove for now.    
#   environment:
#     APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1

- name: Add mono apt repo 
  apt_repository:
    repo: "{{ mono_apt_repo }}"
    state: present
  when: ansible_distribution != "Ubuntu"

- name: Add mono apt repo Ubuntu
  apt_repository:
    repo: "{{ mono_apt_repo_ubuntu }}"
    state: present
  when: ansible_distribution == "Ubuntu"


- name: Install mono
  apt:
    name: "{{ mono_package }}"
    update_cache: yes
    state: latest

- name: Install mono extra packages
  apt:
    name: "{{ mono_extra_packages }}"
    update_cache: yes
    state: latest
  when: "mono_extra_packages is defined"

