---
- name: Add mono yum repo
  yum_repository:
    url: "{{ mono_yum_repo }}"
    gpgkey: "{{ mono_yum_gpgkey }}"
    description: "{{ mono_yum_description }}"
    state: present

- name: Install mono
  yum:
    name: "{{ mono_package }}"
    state: latest
