---
- block:
  - name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}.yml"

  - import_tasks: install-RedHat.yml
    when: "ansible_os_family == 'RedHat'"

  - import_tasks: install-Debian.yml
    when: "ansible_os_family == 'Debian'"
  tags:
    - mono
